# Generated by Django 3.2.4 on 2021-09-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_item_saledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('z', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
    ]
