# Generated by Django 3.2.4 on 2021-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20210916_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='score',
            field=models.PositiveSmallIntegerField(max_length=256),
        ),
    ]
